# Generated by Django 4.2.14 on 2024-08-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="商品ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="商品名稱", max_length=200)),
                ("price", models.IntegerField(help_text="價格")),
                ("status", models.CharField(help_text="商品目前的狀態", max_length=20)),
                ("description", models.TextField(help_text="商品描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="商品創建時間"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="商品更新時間")),
            ],
            options={"db_table": "Items",},
        ),
    ]
