# Generated by Django 4.2.14 on 2024-08-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Item_image",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
