# Generated by Django 5.0.7 on 2024-08-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_item_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Item_image2',
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
